### ISSUE TITLE
Recursive

### ISSUE THREAD

**Issue by kert-io** [jbardin/scp.py#113]
What is the point if it doesn't actually create the dir path?

**Comment by remram44** [comment]
Hi @kert-io,

What is the problem you observed?

**Comment by kert-io** [comment]
Scenario: moving a music library where the artist, album name are nested directories and can contain spaces.  You escape the song names just fine when placing them, but your do not recursively create the path on the remote server.     Thus it fails to copy the file because the path is not present.

**Comment by remram44** [comment]
Do you mean that there is an issue when the directory name (not file name) contains spaces?

**Comment by kert-io** [comment]
`
>>> from paramiko import SSHClient
>>> from scp import SCPClient
>>> def progress(filename, size, sent):
...     sys.stdout.write("%s\'s progress: %.2f%%   \r" % (filename, float(sent)/float(size)*100))
... 
>>> def get_scp_client():
...     ssh = SSHClient()
...     ssh.load_system_host_keys()
...     ssh.connect(’123.123.123.123’, username=‘someone’)
...     return SCPClient(ssh.get_transport(), progress=progress)
... 
>>> scp = get_scp_client()
>>> scp.put('/Volumes/data/music/iTunes/iTunes Music/Damien Rice/9/08 Grey Room.mp3', recursive=True, remote_path='/home/kert/music/Damien Rice/9/08 Grey Room.mp3', preserve_times=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kertheinecke/Documents/Development/media-lib/virtenv/lib/python3.6/site-packages/scp.py", line 152, in put
    self._send_recursive(files)
  File "/Users/kertheinecke/Documents/Development/media-lib/virtenv/lib/python3.6/site-packages/scp.py", line 301, in _send_recursive
    self._send_files([base])
  File "/Users/kertheinecke/Documents/Development/media-lib/virtenv/lib/python3.6/site-packages/scp.py", line 250, in _send_files
    self._send_file(fl, name, mode, size)
  File "/Users/kertheinecke/Documents/Development/media-lib/virtenv/lib/python3.6/site-packages/scp.py", line 260, in _send_file
    self._recv_confirm()
  File "/Users/kertheinecke/Documents/Development/media-lib/virtenv/lib/python3.6/site-packages/scp.py", line 342, in _recv_confirm
    raise SCPException(asunicode(msg[1:]))
scp.SCPException: scp: /home/kert/music/Damien Rice/9/08 Grey Room.mp3: No such file or directory`

**Comment by remram44** [comment]
You seem to have misunderstood what "recursive" means. The option allows to transfer *directories*, not single files, by recursively transferring the files and directories that are inside of it.

If the target directory doesn't exist, it will not be created, whether "recursive" is set or not. This is exactly the same as the command-line scp's `-r` option.
