### ISSUE TITLE
TypeError: ssh_progress() takes exactly 4 arguments (5 given)

### ISSUE THREAD

**Issue by adriass** [jbardin/scp.py#120]
Trying to execute `pyupdater upload --service SCP` fails with an error:
```
Traceback (most recent call last):
  File "c:\users\myuser\workspace\myapp\venv\lib\site-packages\scp_uploader.py", line 142, in upload_file
    self.client.put(filename, remote_path=self.remote_dir)
  File "c:\users\myuser\workspace\myapp\venv\lib\site-packages\scp.py", line 166, in put
    self._send_files(files)
  File "c:\users\myuser\workspace\myapp\venv\lib\site-packages\scp.py", line 270, in _send_files
    self._send_file(fl, name, mode, size)
  File "c:\users\myuser\workspace\myapp\venv\lib\site-packages\scp.py", line 287, in _send_file
    self._progress_tracker(self._progress, basename, size, 0, self.peername)
  File "c:\users\myuser\workspace\myapp\venv\lib\site-packages\scp.py", line 129, in _progress_tracker
    method(basename, size, file_pos, peername)
TypeError: ssh_progress() takes exactly 4 arguments (5 given)
248509 DEBUG: 'SCPUploader' object has no attribute '_connect'
Traceback (most recent call last):
  File "c:\users\myuser\workspace\myapp\venv\lib\site-packages\pyupdater\cli\commands.py", line 432, in _cmd_upload
    pyu.upload()
  File "c:\users\myuser\workspace\myapp\venv\lib\site-packages\pyupdater\core.py", line 94, in upload
    self.up.upload()
  File "c:\users\myuser\workspace\myapp\venv\lib\site-packages\pyupdater\uploader.py", line 133, in upload
    complete = self.uploader.upload_file(f)
  File "c:\users\myuser\workspace\myapp\venv\lib\site-packages\scp_uploader.py", line 147, in upload_file
    self._connect()
AttributeError: 'SCPUploader' object has no attribute '_connect'
248519 ERROR: 'SCPUploader' object has no attribute '_connect'
[ERROR] 'SCPUploader' object has no attribute '_connect'
248682 DEBUG: EOF in transport thread
```

So I changed the `_progress_tracker` (line 123) from `venv/Lib/site-packages/scp.py` to:
```
    def _progress_tracker(self, method, basename, size, file_pos, peername):
        # Count number of arguments.
        count = method.__code__.co_argcount - 1
        if count == 3:
            method(basename, size, file_pos)
        elif count == 4:
            method(basename, size, file_pos, peername)
        else:
            # Do not break, just skip.
            pass
```
And now is working. (I added the `- 1`)

My current `PyUpdater-SCP-Plugin` is on version 3.0.12.
My current `scp` is on version `0.12.0`.
Seems like `co_argcount ` attribute also counts the `self` argument.

**Comment by remram44** [comment]
Sorry about that! Glad to hear that the fix works!

Duplicate of #117
