### ISSUE TITLE
Partial progress callback broken in versions >= 0.11.0 

### ISSUE THREAD

**Issue by mdear** [jbardin/scp.py#121]
There are cases in which it is necessary to specify the callback function as a partial.  This now causes breakage.

```
from paramiko import SSHClient
from scp import SCPClient
from functools import partial
import sys

ssh = SSHClient()
ssh.load_system_host_keys()
ssh.connect('example.com')

# Define progress callback that prints the current percentage completed for the file
def progress(filename, size, sent):
    sys.stdout.write("%s\'s progress: %.2f%%   \r" % (filename, float(sent)/float(size)*100) )

# you can also add 4th parameter to track IP and port
# useful with multiple threads to track source
def progress(filename, size, sent, peername, extra_arg):
    sys.stdout.write("(%s:%s) %s\'s progress: %.2f%%   \r" % (peername[0], peername[1], filename, float(sent)/float(size)*100) )

# SCPCLient takes a paramiko transport and progress callback as its arguments.
scp = SCPClient(ssh.get_transport(), progress = partial(progress, "extra_argument"))

scp.put('test.txt', '~/test.txt')
# Should now be printing the current progress of your put function.

scp.close()


Traceback (most recent call last):
 ...
    scp.get(remote_path=from_path, local_path=to_path)
  File "/venv/lib/python3.4/site-packages/scp.py", line 240, in get
    self._recv_all()
  File "/venv/lib/python3.4/site-packages/scp.py", line 391, in _recv_all
    command[code](msg[1:])
  File "/venv/lib/python3.4/site-packages/scp.py", line 439, in _recv_file
    self._progress_tracker(self._progress, path, size, 0, self.peername)
  File "/venv/lib/python3.4/site-packages/scp.py", line 126, in _progress_tracker
    count = method.__code__.co_argcount
AttributeError: 'functools.partial' object has no attribute '__code__'

```

**Comment by remram44** [comment]
Maybe I should revert #114, it seems it cannot be made reliable.

Or would that cause even more trouble for people?

**Comment by remram44** [comment]
Understood. I will merge #122 and revert to introspection-free logic.

**Comment by mdear** [comment]
Thanks very much for taking care of this.
