### ISSUE TITLE
EOF on write only SFTP

### ISSUE THREAD

**Issue by XioNoX** [jbardin/scp.py#140]
I'm trying to use your library to upload files to an anonymous SFTP repository.
The script is on https://gist.github.com/XioNoX/42a61288c3f638ecd1bbd24b13d6c483 and the doc at  https://kb.juniper.net/InfoCenter/index?page=content&id=KB23337&actp=METADATA

But it fails with the following error:
```
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
INFO:root:Upload logs to JTAC
DEBUG:paramiko.transport:[chan 0] EOF sent (0)
Traceback (most recent call last):
  File "autorsi.py", line 109, in <module>
    main()
  File "autorsi.py", line 105, in main
    file_transfer.upload(args.case)
  File "autorsi.py", line 82, in upload
    scp.put('LOGS-' + utc_date_time + '.tgz', remote_path='/pub/incoming/' + case)
  File "/home/xionox/Documents/Projects/Wikimedia-tinkering/autorsi/env/lib/python3.7/site-packages/scp.py", line 157, in put
    self.sanitize(asbytes(remote_path)))
  File "/home/xionox/Documents/Projects/Wikimedia-tinkering/autorsi/env/lib/python3.7/site-packages/paramiko/channel.py", line 72, in _check
    return func(self, *args, **kwds)
  File "/home/xionox/Documents/Projects/Wikimedia-tinkering/autorsi/env/lib/python3.7/site-packages/paramiko/channel.py", line 257, in exec_command
    self._wait_for_event()
  File "/home/xionox/Documents/Projects/Wikimedia-tinkering/autorsi/env/lib/python3.7/site-packages/paramiko/channel.py", line 1226, in _wait_for_event
    raise e
paramiko.ssh_exception.SSHException: Channel closed.
```

Any pointers on how to solve/workaround the issue is welcome. Let me know if I can provide more troubleshooting.
Thanks!

**Comment by remram44** [comment]
This is an SCP library, not an SFTP library. If your device only supports SFTP then this won't work.

See the docs for paramiko here: https://docs.paramiko.org/en/stable/api/sftp.html
