### ISSUE TITLE
ImportError: cannot import name 'SCPClient'

### ISSUE THREAD

**Issue by zzj0402** [jbardin/scp.py#145]
docker image python:3.6 with scp and paramiko
Run:
```python
from paramiko import SSHClient
from scp import SCPClient

ssh = SSHClient()
ssh.load_system_host_keys()
ssh.connect('example.com')

# SCPCLient takes a paramiko transport as an argument
scp = SCPClient(ssh.get_transport())

scp.put('test.txt', 'test2.txt')
scp.get('test2.txt')

# Uploading the 'test' directory with its content in the
# '/home/user/dump' remote directory
scp.put('test', recursive=True, remote_path='/home/user/dump')

scp.close()
```

```bash
Traceback (most recent call last):
  File "scp.py", line 2, in <module>
    from scp import SCPClient
  File "/workspace/scp.py", line 2, in <module>
    from scp import SCPClient
ImportError: cannot import name 'SCPClient'
```

**Comment by zzj0402** [comment]
On Windows 10 with python 3.8.5:
```
from scp import SCPClient
ImportError: cannot import name 'SCPClient' from partially initialized module 'scp' (most likely due to a circular import) (d:\lz78\scp.py)
```

**Comment by remram44** [comment]
Don't call your script `scp.py`

**Comment by rajatnair05** [comment]
did you get any solution for this problem.

**Comment by remram44** [comment]
Yes, it's the last answer with 15 thumbs up. Don't revive old issues with no new information like this.
