### ISSUE TITLE
Remote wildcard does not work

### ISSUE THREAD

**Issue by AdrienMatricon** [jbardin/scp.py#174]
In my script I have something like this:
```
scp.get("/remote/path/*", "local/path", recursive = True)
```
but this results in an exception (and a warning which I'm not sure is related):
```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amatricon/.local/lib/python3.8/site-packages/scp.py", line 277, in get
    self._recv_all()
  File "/home/amatricon/.local/lib/python3.8/site-packages/scp.py", line 429, in _recv_all
    raise SCPException(asunicode(msg[1:]))
scp.SCPException: scp: /remote/path/*: No such file or directory
```
This is not the expected behavior, since `scp username@host:'/remote/path/*' local/path` works, and the comment in `scp.py` explicitly states :
```
@param remote_path: path to retrieve from remote host. since this is
            evaluated by scp on the remote host, shell wildcards and
            environment variables may be used.
```

**Comment by remram44** [comment]
You're right, those get escaped now. You can use them if you change the `sanitize` function:

```python
scp = SCPClient(ssh.get_transport(), sanitize=lambda x: x)
scp.get(...)
```

Note that you will have to do your own escaping then, for example if there are spaces in filenames (or `*` or `\`)

I will update the docstring, thanks!

**Comment by remram44** [comment]
Docstring updated with 97645a02.
