### ISSUE TITLE
socket.timeout

### ISSUE THREAD

**Issue by ahireajay** [jbardin/scp.py#36]
Hello,

I am facing issue during transfer of a file of size ~ 200MB. scp.put fails with below error:

Traceback (most recent call last): File "C:\Python27\lib\site-packages\robot\running\timeouts.py", line 85, in run return runner.get_result() 
File "C:\Python27\lib\site-packages\robot\utils\robotthread.py", line 37, in run self._result = self._runnable()
 File "C:\Python27\lib\site-packages\robot\utils\robotthread.py", line 28, in <lambda> self._runnable = lambda: runnable(*(args or ()), **(kwargs or {})) 
File "C:\Documents and Settings\test1\libs\UpgradeBuild.py", line 12, in UpgradeBuild scp.put(BuildLocation,DestLocation )
 File "build\bdist.win32\egg\scp.py", line 103, in put self._send_files(files)
 File "build\bdist.win32\egg\scp.py", line 181, in _send_files chan.sendall(file_hdl.read(buff_size)) File "C:\Python27\lib\site-packages\paramiko\channel.py", line 765, in sendall sent = self.send(s) File "C:\Python27\lib\site-packages\paramiko\channel.py", line 690, in send size = self._wait_for_send_window(size)
 File "C:\Python27\lib\site-packages\paramiko\channel.py", line 1177, in _wait_for_send_window raise socket.timeout()

**Comment by xduvox** [comment]
Hello jbardin could you help me with this: 

Traceback (most recent call last):
  File "getCurrent.py", line 14, in <module>
    scp.get(remote_path='/home/webcdr/cdr_data', local_path='/root/vosmonitor/vos1', recursive=True, preserve_times=False)
  File "/usr/local/lib/python2.7/dist-packages/scp.py", line 143, in get
    self._recv_all()
  File "/usr/local/lib/python2.7/dist-packages/scp.py", line 274, in _recv_all
    command[code](msg[1:])
  File "/usr/local/lib/python2.7/dist-packages/scp.py", line 337, in _recv_file
    raise SCPException('Error receiving, socket.timeout')
scp.SCPException: Error receiving, socket.timeout

**Comment by xduvox** [comment]
With a simple file i get the same result
Traceback (most recent call last):
  File "getCurrent.py", line 14, in <module>
    scp.get('/home/webcdr/cdr_data/cdr_20150113000000_20150113001500.tsv.gz', local_path='/root/vosmonitor/vos1/cdr_20150113000000_20150113001500.tsv.gz')
  File "/usr/local/lib/python2.7/dist-packages/scp.py", line 143, in get
    self._recv_all()
  File "/usr/local/lib/python2.7/dist-packages/scp.py", line 274, in _recv_all
    command[code](msg[1:])
  File "/usr/local/lib/python2.7/dist-packages/scp.py", line 337, in _recv_file
    raise SCPException('Error receiving, socket.timeout')
scp.SCPException: Error receiving, socket.timeout

**Comment by jbardin** [comment]
If you're still having a problem, please try the latest release.

It doesn't look like an scp issue, but I'm not ruling it out completely. Is the remote server running openssh's version of scp?
