### ISSUE TITLE
unit tests fail on osx

### ISSUE THREAD

**Issue by jbardin** [jbardin/scp.py#49]
```
Running tests on Mac OS X with Python 2
....FF
======================================================================
FAIL: test_put_bytes (__main__.TestUpload)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 228, in test_put_bytes
    self.upload_test(b'cl\xC3\xA9/r\xC3\xA9mi', False, [b'r\xC3\xA9mi'])
  File "test.py", line 219, in upload_test
    self.assertEqual(set(out_list), set(expected))
AssertionError: Items in the first set but not the second:
're\xcc\x81mi'
Items in the second set but not the first:
'r\xc3\xa9mi'

======================================================================
FAIL: test_put_unicode (__main__.TestUpload)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 238, in test_put_unicode
    self.upload_test(u'cl\xE9/r\xE9mi', False, [b'r\xC3\xA9mi'])
  File "test.py", line 219, in upload_test
    self.assertEqual(set(out_list), set(expected))
AssertionError: Items in the first set but not the second:
're\xcc\x81mi'
Items in the second set but not the first:
'r\xc3\xa9mi'
```

**Comment by remram44** [comment]
This seems to fix it:
```diff
@@ -216,7 +216,7 @@ class TestUpload(unittest.TestCase):
             prefix = len(destination) + 1
             out_list = [l[prefix:] for l in out_list.splitlines()
                         if len(l) > prefix]
-            self.assertEqual(set(out_list), set(expected))
+            self.assertEqual(normalize_paths(out_list), set(expected))
         finally:
             os.chdir(previous)
             chan = self.ssh.get_transport().open_session()
```

**Comment by jbardin** [comment]
ah, there it is. thanks!
