### ISSUE TITLE
Nested exceptions when trying to get non-existent file

### ISSUE THREAD

**Issue by Grazfather** [jbardin/scp.py#60]
Tested on 0.8.0 and 0.10.0 on OSX, python 3.4

```
$ python3
Python 3.4.1 (v3.4.1:c0e311e010fc, May 18 2014, 00:54:21)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import paramiko
>>> import scp
>>> sshClient = paramiko.SSHClient()
>>> sshClient.load_system_host_keys()
>>> sshClient.set_missing_host_key_policy(paramiko.AutoAddPolicy())
>>> sshClient.connect("127.0.0.1", username="root", password="alpine", port=3333)
>>> scpClient = scp.SCPClient(sshClient.get_transport())
>>> scpClient.get("decryptedAPPs/RefMe")
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/scp.py", line 323, in _recv_all
    command[code](msg[1:])
KeyError: b'\x01'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/scp.py", line 190, in get
    self._recv_all()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/scp.py", line 325, in _recv_all
    raise SCPException(str(msg).strip())
scp.SCPException: b'\x01scp: decryptedAPPs/RefMe: No such file or directory'
>>>
```

**Comment by Grazfather** [comment]
I get the same errors when I try to get a dir, just the message is different.

**Comment by remram44** [comment]
I think this is supposed to happen. The SCPException gets raised on purpose, Python 3 chains it with the KeyError.

I don't know if there is a way to disable chaining, "from None" would break PY2 compatibility.

**Comment by Grazfather** [comment]
I think the problem is that the 'msg' is being interpreted as a dictionary or something instead of as a list. I will dig into it more tomorrow. I really don't think a KeyError should be what makes its way out of the scp module.

**Comment by remram44** [comment]
No, ̀command` is the dictionary. Instead of a command, the server sends b'\x01' which indicates an error. I think this works as intended.

**Comment by Grazfather** [comment]
Yes. Took a look. You even catch the `KeyError`. I wouldn't expect two stack traces in this case, and would hope for 'just' the `SCPException`.

**Comment by remram44** [comment]
Agreed!

**Comment by Grazfather** [comment]
Thanks for taking a look :)
