### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by Asdoos** [jbardin/scp.py#85]
If I try to install this module i get a few errors:

```
Traceback (most recent call last):
  File "C:\Python27\Scripts\pip-script.py", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 542, in l
oad_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2569, in
load_entry_point
    return ep.load()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2229, in
load
    return self.resolve()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2235, in
resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Python27\lib\site-packages\pip\__init__.py", line 13, in <module>
    from pip.commands import commands, get_summaries, get_similar_commands
  File "C:\Python27\lib\site-packages\pip\commands\__init__.py", line 6, in <mod
ule>
    from pip.commands.bundle import BundleCommand
  File "C:\Python27\lib\site-packages\pip\commands\bundle.py", line 6, in <modul
e>
    from pip.commands.install import InstallCommand
  File "C:\Python27\lib\site-packages\pip\commands\install.py", line 5, in <modu
le>
    from pip.req import InstallRequirement, RequirementSet, parse_requirements
  File "C:\Python27\lib\site-packages\pip\req\__init__.py", line 3, in <module>
    from .req_install import InstallRequirement
  File "C:\Python27\lib\site-packages\pip\req\req_install.py", line 33, in <modu
le>
    from pip.utils import (
  File "C:\Python27\lib\site-packages\pip\utils\__init__.py", line 100, in <modu
le>
    def rmtree(dir, ignore_errors=False):
  File "C:\Python27\lib\site-packages\pip\_vendor\retrying.py", line 47, in wrap
    @six.wraps(f)
AttributeError: 'module' object has no attribute 'wraps'
```

or with python setup.py install:

```
C:\Users\User1\Desktop\scp.py-master>python setup.
py install
running install
running bdist_egg
running egg_info
writing requirements to scp.egg-info\requires.txt
writing scp.egg-info\PKG-INFO
writing top-level names to scp.egg-info\top_level.txt
writing dependency_links to scp.egg-info\dependency_links.txt
reading manifest file 'scp.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'scp.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
creating build\bdist.win32\egg
copying build\lib\scp.py -> build\bdist.win32\egg
byte-compiling build\bdist.win32\egg\scp.py to scp.pyc
creating build\bdist.win32\egg\EGG-INFO
copying scp.egg-info\PKG-INFO -> build\bdist.win32\egg\EGG-INFO
copying scp.egg-info\SOURCES.txt -> build\bdist.win32\egg\EGG-INFO
copying scp.egg-info\dependency_links.txt -> build\bdist.win32\egg\EGG-INFO
copying scp.egg-info\requires.txt -> build\bdist.win32\egg\EGG-INFO
copying scp.egg-info\top_level.txt -> build\bdist.win32\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist\scp-0.10.2-py2.7.egg' and adding 'build\bdist.win32\egg' to it
removing 'build\bdist.win32\egg' (and everything under it)
Processing scp-0.10.2-py2.7.egg
Removing c:\python27\lib\site-packages\scp-0.10.2-py2.7.egg
Copying scp-0.10.2-py2.7.egg to c:\python27\lib\site-packages
scp 0.10.2 is already the active version in easy-install.pth

Installed c:\python27\lib\site-packages\scp-0.10.2-py2.7.egg
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    install_requires = ['paramiko'],
  File "C:\Python27\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\site-packages\setuptools\command\install.py", line 67, i
n run
    self.do_egg_install()
  File "C:\Python27\lib\site-packages\setuptools\command\install.py", line 117,
in do_egg_install
    cmd.run()
  File "C:\Python27\lib\site-packages\setuptools\command\easy_install.py", line
370, in run
    self.easy_install(spec, not self.no_deps)
  File "C:\Python27\lib\site-packages\setuptools\command\easy_install.py", line
594, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "C:\Python27\lib\site-packages\setuptools\command\easy_install.py", line
645, in install_item
    self.process_distribution(spec, dist, deps)
  File "C:\Python27\lib\site-packages\setuptools\command\easy_install.py", line
688, in process_distribution
    distreq.project_name, distreq.specs, requirement.extras
TypeError: __init__() takes exactly 2 arguments (4 given)

```

**Comment by remram44** [comment]
Looks like your setuptools installation is broken.
